### ISSUE TITLE
Relative path not working for img tag

### ISSUE THREAD

**Issue by flaminghot-cheesepuff** [flaminghot-cheesepuff/code-a-website#1]
Hi, I can't figure out what is wrong with my code for the img tag. When I use the relative path for the image, the image is not showing up on the website. It's the same for all the pages.

@hellachella
@anna-pokhilenko

**Comment by hellachella** [comment]
Your images are in the folder above this one (berries folder). you need to get out of the berrier folder and into the image folder.  to do that (move out of a folder) you need to use `../`

`<img src="../images/bananas.jpg">`
